### ISSUE TITLE
errors when loading on Chrome

### ISSUE THREAD

**Issue by cslamo** [inciteful-xyz/inciteful-zotero-plugin#1]
Got these 2 errors:
Unrecognized manifest key 'applications'.

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

Using Chrome on Windows 10.

**Comment by weishuhn** [comment]
This plugin should be installed on Zotero and not Chrome.  The Zotero chrome plugin can be found [here](https://chrome.google.com/webstore/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc?hl=en).
