### ISSUE TITLE
Graph Search fails for multiple papers when one does not have records in Inciteful

### ISSUE THREAD

**Issue by davelsan** [inciteful-xyz/inciteful-zotero-plugin#16]
### Description

Using Graph Search with multiple papers selected, the search will fail as if no papers had been selected when even just one of them does not have any references or citations in Inciteful. See the following image for an example of what the website shows in such a situation.

<img width=300 src="https://github.com/inciteful-xyz/inciteful-zotero-plugin/assets/7377316/02bc5de5-b0ec-44d5-9fcd-0969d9c3419b" alt="Image showing the Inciteful.xyz website attempting to create a graph with no papers">

### Reproduce

Select several papers and use the contextual menu to execute a _Graph Search_. Make sure that at least one of the papers does not have records in Inciteful.

<img width=300 src="https://github.com/inciteful-xyz/inciteful-zotero-plugin/assets/7377316/d4c18c25-05d6-4ef3-b282-1906652d008d" alt="Image showing multiple papers selected in Zotero. The contextual menu of Inciteful.xyz is open with the Graph Search option being hovered. Two papers that cause this issue are expanded.">

You can verify that a paper does not have records by trying to do a Graph Search with only that paper. The following error will show on the Inciteful website.

> We could not construct the graph. We don't have records of any references or citations for this paper, which makes it kind of hard. Please search for another paper.

Two papers for which Inciteful does not have records at the time of creating this issue are:
- Ford, James D., Tristan Pearce, Frank Duerden, Chris Furgal, and Barry Smit. “Climate Change Policy Responses for Canada’s Inuit Population: The Importance of and Opportunities for Adaptation.” Global Environmental Change 20, no. 1 (February 2010): 177–91. https://doi.org/10.1016/j.gloenvcha.2009.10.008.
- Schæbel, L. H., H. Vestergaard, P. Laurberg, C. N. Rathcke, and S. Andersen. “Intake of Traditional Inuit Diet Vary in Parallel with Inflammation as Estimated from YKL-40 and HsCRP in Inuit and Non-Inuit in Greenland.” Atherosclerosis 228, no. 2 (June 1, 2013): 496–501. https://doi.org/10.1016/j.atherosclerosis.2013.03.022.

### Expected Behavior

- [Functionality] Inciteful should attempt to create a graph with the papers for which it has records.
- [UX] Feedback should be provided to the user about the papers which could not be used to generate a graph, either in Zotero, Inciteful website, or both.

**Comment by hogru** [comment]
Promoting this since I just stumbled upon the issue after having tried to figure it out. As a side note, (as probably expected) it does not matter if you (try to) build the graph via Zotero or import a BibTeX file via the Inciteful website.

**Comment by weishuhn** [comment]
Thanks for bringing this up and sorry about the delay in responding. I'm pretty slammed right now so might be a bit slow in fixing it.  But I hope to get to it this week or next.  Thanks!

**Comment by FeralFlora** [comment]
Yeah, as @hogru mentions, this seems like the same issue I raised on the web interface repo: https://github.com/inciteful-xyz/inciteful-web/issues/37.

**Comment by weishuhn** [comment]
Sorry for the long delay on this. It should be fixed now.  It was a problem with the OpenAlex API.  They changed the signature and one of the API calls was failing.

**Comment by hogru** [comment]
Just tried it, and it works beautifully now. Thanks!
