### ISSUE TITLE
Can this work in zotero 7?

### ISSUE THREAD

**Issue by jlu511** [inciteful-xyz/inciteful-zotero-plugin#17]
Can this work in zotero 7?

**Comment by weishuhn** [comment]
It was working in the beta when I first released it this spring.  So it
should still work.  Let me know if it doesn't. Thanks!

**Comment by jlu511** [comment]
When Zotero 7 is set to English, a menu appears when you right-click on an item. However, when Zotero 7 is set to another language, such as Chinese, there is no menu that appears when you right-click on an item.

**Comment by weishuhn** [comment]
Try reinstalling the plugin.  I just added a default_locale option to the manifest.  Also, if you would be willing, I would love for you to create a Chinese translation.  You would just need to add copy the `addon/chrome/locale/en-US`, translate the values there, and submit a pull request.

**Comment by jlu511** [comment]
> Try reinstalling the plugin. I just added a default_locale option to the manifest. Also, if you would be willing, I would love for you to create a Chinese translation. You would just need to add copy the `addon/chrome/locale/en-US`, translate the values there, and submit a pull request.

thank you for releasing 0.0.9. However,  when I reinstall the 0.0.9 plugin, It is not compatible with this version of Zotero.

![image](https://github.com/inciteful-xyz/inciteful-zotero-plugin/assets/64378673/57803d30-9421-42ae-a78b-437f0e2001d2)

I can create Chinese translations, but I don't understand programming or how to submit a PR. Therefore, could you provide an English template for me to translate into Chinese?"

**Comment by jlu511** [comment]
menuitem.main=Inciteful.xyz Tools (Inciteful.xyz 工具)
menuitem.search=Graph Search （图形搜索）
menuitem.connector=Connect Papers （链接论文）
collectionitem.search=Graph Search using Inciteful.xyz （使用Inciteful.xyz的图形搜索）
tabpanel.lib.tab.label=Inciteful
error.noItemSelected=Please select at least one item with a DOI. （请至少选择一个具有DOI的条目）
error.connector.toomany=You can only connect two items at a time. （一次只能连接两个条目）

<!ENTITY zotero.__addonRef__.pref.title "Addon Template Example （插件模板示例）">
<!ENTITY zotero.__addonRef__.itemmenu.test.label "addon template（插件模板）">
<!ENTITY zotero.__addonRef__.pref.enable.label "Enable （启用）">
<!ENTITY zotero.__addonRef__.pref.input.label "Input （输入）">

<!ENTITY zotero.__addonRef__.help.version.label "__addonName__ VERSION __buildVersion__ （__插件名称__版本__构建版本__）">
<!ENTITY zotero.__addonRef__.help.releasetime.label "Build __buildTime__(构建__构建时间__)">

**Comment by jlu511** [comment]
<!ENTITY zotero.__addonRef__.pref.title "Addon Template Example （插件模板示例）">
<!ENTITY zotero.__addonRef__.itemmenu.test.label "addon template（插件模板）">
<!ENTITY zotero.__addonRef__.pref.enable.label "Enable （启用）">
<!ENTITY zotero.__addonRef__.pref.input.label "Input （输入）">

<!ENTITY zotero.__addonRef__.help.version.label "__addonName__ VERSION __buildVersion__ （__插件名称__版本__构建版本__）">
<!ENTITY zotero.__addonRef__.help.releasetime.label "Build __buildTime__(构建__构建时间__)">

**Comment by seanhu0401** [comment]
When I tried to install the add-on in Zotero 7, it has the error for incompatible versioning with Zotero. Zotero is in English.

Zotero Version: 7.0.0-beta.53+969031a37
Add-on version: 0.0.9

Thank you.

**Comment by weishuhn** [comment]
Just getting around to testing this out.  It looks they changed the plugin system midway through the beta and the plugin no longer works with the current beta.  I'll try to get to this in the coming days.

**Comment by Levling** [comment]
Thank you so much for doing this! I love inciteful and it would be amazing if I could use it with the latest Zotero beta as well.

**Comment by FeralFlora** [comment]
Zotero 7 was released out of beta today, so hopefully that gives some confidence that the Zotero 7 internals have stabilized now.

**Comment by gabrielmacedoanac** [comment]
Doesnt work until now in Zotero 7.

**Comment by weishuhn** [comment]
Finally got to updating for Zotero 7.  You'll have to reinstall the addon from [the release page](https://github.com/inciteful-xyz/inciteful-zotero-plugin/releases/tag/v0.1.0). Let me know if you have any problems.
