### ISSUE TITLE
[Bug]：Version compatibility issues with zotero7 ——>[ 7.0.0-beta.54+6b996d4f9 (64-bit)]

### ISSUE THREAD

**Issue by August-L-J** [inciteful-xyz/inciteful-zotero-plugin#20]
My Windows system: Win 10,22H2
Zotero version: 7.0.0-beta.54+6b996d4f9 (64-bit)
The problem: An error was reported in the process of adding the plugin to Zotero, unable to add, incompatible, hope this issue will be resolved soon:)

**Comment by weishuhn** [comment]
Just getting around to testing this out.  It looks they changed the plugin system midway through the beta and the plugin no longer works with the current beta.  I'll try to get to this in the coming days.

**Comment by jlu511** [comment]
0.0.8 works

**Comment by weishuhn** [comment]
Finally got to updating for Zotero 7.  You'll have to reinstall the addon from [the release page](https://github.com/inciteful-xyz/inciteful-zotero-plugin/releases/tag/v0.1.0). Let me know if you have any problems.
