### ISSUE TITLE
Cannot run in macOS version of zotero7

### ISSUE THREAD

**Issue by DayuGuo** [inciteful-xyz/inciteful-zotero-plugin#21]
Thank you for providing such a great plugin.

Report an error: The add-on could not be installed. It may be incompatible with this version of Zotero.

Zotero version number: 7.0.0-beta.68+c31a40c74

Computer system：macOS 14.4 (23E214)

If testing or assistance is needed I'll be happy to help. email: hi@anotherdayu.com

**Comment by phren0logy** [comment]
I get the same error, and would also be happy to help with testing.

**Comment by weishuhn** [comment]
Finally got to updating for Zotero 7.  You'll have to reinstall the addon from [the release page](https://github.com/inciteful-xyz/inciteful-zotero-plugin/releases/tag/v0.1.0). Let me know if you have any problems.
