### ISSUE TITLE
Incompatible with Zotero 7.0 / Hopefully not Abandoned

### ISSUE THREAD

**Issue by LordDerMoff** [inciteful-xyz/inciteful-zotero-plugin#22]
The Zotero 7 beta is finished, but sadly the plugin doesn't work anymore in the full, stable version (shows message that plugin is incompatible with Zotero)

It would be such a shame if something so wonderful as this Website and Plugin would not work anymore.
It is quite literally — with AA — the most useful Website for Academia.

I do see that there was no development anymore since summer last year. I hope it was just a loose of interest and nothing too serious!
If it was the former, I beg you to reconsider — this is a marvelous work! The sole reason I would want to improve/learn coding right now is to be able to maintain this via pull request.

**Comment by weishuhn** [comment]
I appreciate the kind comments, it's not abandoned and I'm hoping to get to it in the next few weeks.

**Comment by weishuhn** [comment]
Finally got to it.  You'll have to reinstall the addon from [the release page](https://github.com/inciteful-xyz/inciteful-zotero-plugin/releases/tag/v0.1.0). Let me know if you have any problems.

**Comment by LordDerMoff** [comment]
I tested it and it works like a charm! Thanks again for this incredibly useful tool 🥇
